/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./sidepanel/**/*.{html,js}", "./content/**/*.{html,js}", "./*.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#d9ffef",
        "surface-container": "#172127",
        "secondary-fixed": "#92f5d9",
        "tertiary": "#bcc8cf",
        "primary-fixed-dim": "#59dcb5",
        "on-primary-fixed-variant": "#00513e",
        "primary-container": "#008064",
        "surface-bright": "#303b41",
        "surface-container-low": "#131d23",
        "secondary-container": "#03816a",
        "background": "#0a151a",
        "on-primary": "#00382a",
        "on-error-container": "#ffdad6",
        "on-secondary-container": "#e1fff3",
        "inverse-on-surface": "#283238",
        "surface-container-high": "#212b32",
        "outline-variant": "#3e4945",
        "surface-tint": "#59dcb5",
        "surface-container-highest": "#2c363d",
        "on-tertiary-container": "#eef8ff",
        "on-tertiary-fixed": "#121d22",
        "on-secondary": "#00382c",
        "secondary-fixed-dim": "#76d8bd",
        "on-surface": "#d9e4ec",
        "inverse-surface": "#d9e4ec",
        "inverse-primary": "#006b53",
        "outline": "#87938e",
        "surface": "#0a151a",
        "primary-fixed": "#79f9d0",
        "surface-variant": "#2c363d",
        "on-tertiary": "#273238",
        "tertiary-fixed": "#d8e4ec",
        "error-container": "#93000a",
        "on-secondary-fixed-variant": "#005141",
        "surface-dim": "#0a151a",
        "on-error": "#690005",
        "on-background": "#d9e4ec",
        "on-tertiary-fixed-variant": "#3d484e",
        "error": "#ffb4ab",
        "tertiary-fixed-dim": "#bcc8cf",
        "on-secondary-fixed": "#002019",
        "primary": "#59dcb5",
        "tertiary-container": "#677379",
        "on-primary-fixed": "#002117",
        "secondary": "#76d8bd",
        "surface-container-lowest": "#060f15",
        "on-surface-variant": "#bdc9c4"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [],
}
